package com.myspace.wfhrequest_portal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Reason")
	private java.lang.String reason;
	@org.kie.api.definition.type.Label(value = "Request Date")
	private java.time.LocalDate requestDate;
	@org.kie.api.definition.type.Label(value = "Number Of Days")
	private java.lang.Integer numOfDays;

	public Request() {
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public java.time.LocalDate getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(java.time.LocalDate requestDate) {
		this.requestDate = requestDate;
	}

	public java.lang.Integer getNumOfDays() {
		return this.numOfDays;
	}

	public void setNumOfDays(java.lang.Integer numOfDays) {
		this.numOfDays = numOfDays;
	}

	public Request(java.lang.String reason, java.time.LocalDate requestDate,
			java.lang.Integer numOfDays) {
		this.reason = reason;
		this.requestDate = requestDate;
		this.numOfDays = numOfDays;
	}

}